-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 15:35:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotitube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spotitube` ;

-- -----------------------------------------------------
-- Schema spotitube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotitube` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `spotitube` ;

-- -----------------------------------------------------
-- Table `spotitube`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotitube`.`account` ;

CREATE TABLE IF NOT EXISTS `spotitube`.`account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `spotitube`.`library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotitube`.`library` ;

CREATE TABLE IF NOT EXISTS `spotitube`.`library` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `length` INT(11) NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `username`),
  INDEX `account_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `account`
    FOREIGN KEY (`username`)
    REFERENCES `spotitube`.`account` (`user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `spotitube`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotitube`.`playlist` ;

CREATE TABLE IF NOT EXISTS `spotitube`.`playlist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `owner` TINYINT(4) NOT NULL DEFAULT 0,
  `library_id` INT NOT NULL,
  PRIMARY KEY (`id`, `library_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `library_id_idx` (`library_id` ASC) VISIBLE,
  CONSTRAINT `library_id`
    FOREIGN KEY (`library_id`)
    REFERENCES `spotitube`.`library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `spotitube`.`track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotitube`.`track` ;

CREATE TABLE IF NOT EXISTS `spotitube`.`track` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `performer` VARCHAR(45) NOT NULL,
  `duration` INT(11) NOT NULL,
  `playcount` INT(11) NOT NULL,
  `offlineAvailable` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) INVISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `spotitube`.`songtrack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotitube`.`songtrack` ;

CREATE TABLE IF NOT EXISTS `spotitube`.`songtrack` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `album` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `songtrack_id`
    FOREIGN KEY (`id`)
    REFERENCES `spotitube`.`track` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `spotitube`.`token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotitube`.`token` ;

CREATE TABLE IF NOT EXISTS `spotitube`.`token` (
  `token` VARCHAR(255) NOT NULL,
  `account_user` VARCHAR(45) NOT NULL,
  `expiry_date` DATETIME NOT NULL,
  PRIMARY KEY (`token`, `account_user`),
  INDEX `user_idx` (`account_user` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`account_user`)
    REFERENCES `spotitube`.`account` (`user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `spotitube`.`playlist_has_tracks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotitube`.`playlist_has_tracks` ;

CREATE TABLE IF NOT EXISTS `spotitube`.`playlist_has_tracks` (
  `playlist_id` INT(11) NOT NULL,
  `track_id` INT(11) NOT NULL,
  PRIMARY KEY (`playlist_id`, `track_id`),
  INDEX `track_id_idx` (`track_id` ASC) VISIBLE,
  CONSTRAINT `playlist_id`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `spotitube`.`playlist` (`id`),
  CONSTRAINT `track_id`
    FOREIGN KEY (`track_id`)
    REFERENCES `spotitube`.`track` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `spotitube`.`videotrack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotitube`.`videotrack` ;

CREATE TABLE IF NOT EXISTS `spotitube`.`videotrack` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `publicationDate` DATE NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) INVISIBLE,
  CONSTRAINT `videotrack_id`
    FOREIGN KEY (`id`)
    REFERENCES `spotitube`.`track` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

USE `spotitube` ;

-- -----------------------------------------------------
-- Placeholder table for view `spotitube`.`tracks_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotitube`.`tracks_view` (`id` INT, `title` INT, `performer` INT, `duration` INT, `playcount` INT, `offlineAvailable` INT, `album` INT, `publicationDate` INT, `description` INT);

-- -----------------------------------------------------
-- View `spotitube`.`tracks_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotitube`.`tracks_view`;
DROP VIEW IF EXISTS `spotitube`.`tracks_view` ;
USE `spotitube`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `spotitube`.`tracks_view` AS select `spotitube`.`track`.`id` AS `id`,`spotitube`.`track`.`title` AS `title`,`spotitube`.`track`.`performer` AS `performer`,`spotitube`.`track`.`duration` AS `duration`,`spotitube`.`track`.`playcount` AS `playcount`,`spotitube`.`track`.`offlineAvailable` AS `offlineAvailable`,`spotitube`.`songtrack`.`album` AS `album`,`spotitube`.`videotrack`.`publicationDate` AS `publicationDate`,`spotitube`.`videotrack`.`description` AS `description` from ((`spotitube`.`track` left join `spotitube`.`songtrack` on((`spotitube`.`songtrack`.`id` = `spotitube`.`track`.`id`))) left join `spotitube`.`videotrack` on((`spotitube`.`videotrack`.`id` = `spotitube`.`track`.`id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
